# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

platform :ios, '13.0'
use_frameworks!

target 'wowCastillaLeonTour' do
  pod 'MapboxMaps', '>= 10.0.0'
end
